GET http://localhost:3000/api/users

###

//Buscar por nombre
GET https://bikers1.herokuapp.com/api/users


###

//Buscar por username

GET http://localhost:3000/api/users/alias/javiergarcia

###
GET https://bikers1.herokuapp.com/api/users/alias/javiergarcia

###

//Eliminar usuario por id
DELETE http://localhost:3000/api/users/9

###

//Modificar usuario
PUT http://localhost:3000/api/users/8
Content-Type: application/json

{
    "nombre": "Juana",
     "apellidos":"Gonzalez",
     "username":"juanagonz",
     "email":"juana@gmail.com",
     "password":"123457",
     "ciudad":"Albacete",
     "fecha_nacimiento":"1990-11-07",
     "imagen":"https://i.pinimg.com/originals/b4/a0/b3/b4a0b3c05fc729b0f8a9aeb7f545ad44.jpg"
}
###
 //crear usuario
POST https://bikers1.herokuapp.com/api/users   
Content-Type: application/json

 {
     "nombre": "Javiercin",
     "apellidos":"Garia",
     "username":"fbhgxnx6",
     "email":"lucia@gmail.com",
     "password":"123453",
     "ciudad":"Madrid",
     "fecha_nacimiento":"1990-11-07",
     "imagen":"https://i.pinimg.com/originals/b4/a0/b3/b4a0b3c05fc729b0f8a9aeb7f545ad44.jpg"
 }


###
//crear post
POST  https://bikers1.herokuapp.com/api/post/12
Content-Type: application/json

{
    "titulo": "titulo1",
    "descripcion": "En un lugar de la mancha"
   
}




###

POST https://bikers1.herokuapp.com/api/users/login
Content-Type: application/json

{
    "email": "ramonita@gmail.com",
    "password": "1234"
}

###
//Obtener id a partir del email
GET https://bikers1.herokuapp.com/api/users/id/ramonita@gmail.com

###
//Obtener el usuario completo a partir del email

GET http://bikers1.herokuapp.com/api/users/email/ramonita@gmail.com

###










 





 

 



 