###
GET http://localhost:3000/api/posts/3

###
POST http://localhost:3000/api/registrados/registro
Content-Type: application/json

{
    "username": "Adolfo",
    "email": "adolfete@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/registrados/login
Content-Type: application/json

{
    "email": "adolfete@gmail.com",
    "password": "12345"
}

###

//Obtencion post de los amigos

GET http://bikers1.herokuapp.com/api/posts/home/121

###

GET http://bikers1.herokuapp.com/api/posts/1

###

GET https://bikers1.herokuapp.com/api/blog

###

GET https://bikers1.herokuapp.com/api/blog/1

###
GET https://bikers1.herokuapp.com/api/users/get/291

###

//Obtener amigos del 121

GET https://bikers1.herokuapp.com/api/amigos/121